export interface MomentExport {
  tStart: number;
  tEnd: number;
  taskId: string;
  taskLabel?: string;
  frictionPeak: number;
  candidateFindingLabel?: string;
  category?: string;
  interpretation?: string;
  recommendations?: string[];
  signalTags: string[];
  evidence: { transcriptSnippets: string[] };
}

export interface ReportData {
  studyTitle: string;
  sessionId: string;
  endedAt: number;
  themes: string[];
  sessionFriction: number;
  moments: MomentExport[];
}

const fmtTime = (sec: number) => `${Math.floor(sec / 60)}:${String(Math.floor(sec % 60)).padStart(2, "0")}`;

export function generateMarkdownReport(data: ReportData): string {
  const date = new Date(data.endedAt).toLocaleDateString();
  const lines: string[] = [
    `# Unfiltered — UX Research Report`,
    ``,
    `**Study:** ${data.studyTitle}  `,
    `**Session:** ${data.sessionId}  `,
    `**Date:** ${date}  `,
    `**Session Friction Score:** ${data.sessionFriction}/100`,
    ``,
    `---`,
    ``,
    `## Top Friction Themes`,
    ``,
    ...data.themes.map((t, i) => `${i + 1}. ${t}`),
    ``,
    `---`,
    ``,
    `## Friction Moments (${data.moments.length})`,
    ``,
  ];

  for (const m of data.moments) {
    lines.push(`### ${m.candidateFindingLabel ?? "Friction Moment"}`);
    lines.push(`**Time:** ${fmtTime(m.tStart)} – ${fmtTime(m.tEnd)} · **Task:** ${m.taskLabel ?? m.taskId} · **Peak:** ${m.frictionPeak}/100`);
    if (m.category) lines.push(`**Category:** ${m.category.replace(/_/g, " ")}`);
    if (m.interpretation) lines.push(`\n${m.interpretation}`);
    if (m.evidence.transcriptSnippets[0]) lines.push(`\n> "${m.evidence.transcriptSnippets[0]}"`);
    if (m.signalTags.length) lines.push(`\n**Signals:** ${m.signalTags.join(", ")}`);
    if (m.recommendations?.length) {
      lines.push(`\n**Recommendations:**`);
      for (const r of m.recommendations) lines.push(`- ${r}`);
    }
    lines.push(`\n---\n`);
  }

  lines.push(`*Generated by Unfiltered — probabilistic attention flags, not diagnoses.*`);
  return lines.join("\n");
}
